### PR TITLE
Helm chart fixes

### LINKED ISSUE #184: Unable to deploy Kibana with newer Kubernetes
The deployment of Kibana reports the following message:

```
Deployment.extensions "" not found
```

This is mainly because we're not using `apps/v1` inside of the deployment manifest (which has been around since 1.9.0)

### LINKED ISSUE #185: Unable to deploy ElasticSearch with newer Kubernetes
The primary reason is because it's using a legacy and deprecated `apiVersion` of `extensions/v1beta1`.

This has been replaced by `policy/v1beta1` since 1.10.

### PR DESCRIPTION
**Pull request by mnaser**
*Issue #, if available:*

Fixes #184
Fixes #185

*Description of changes:*

Several fixes to support newer versions of Kubernetes.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by smlx** [comment]
Looks like this is a subset of #148

**Comment by rhysjtevans** [comment]
Hi folks, when is this likely to get merged?

**Comment by smlx** [comment]
hey @rhysjtevans it already is over here: https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm

this repo is just a placeholder or something :shrug:

**Comment by rhysjtevans** [comment]
Great got it, thanks @smlx ! 😄

**Comment by rhysjtevans** [comment]
Happy to close this issue

**Comment by bbarani** [comment]
Closing this issue as its already merged here : https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm

Please feel free to open this again if needed.

**Pull request closed without merging**
